[connections.gsheets]
type = "service_account"
project_id = "ticketing-system-495908"
private_key_id = "0a069b8cd4f956542c91549804dfcc479aa48d1e"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMFm7+Uk7m8EDB
...
-----END PRIVATE KEY-----
"""
client_email = "streamlit-bot@ticketing-system-495908.iam.gserviceaccount.com"
client_id = "110048477330643307496"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bot@ticketing-system-495908.iam.gserviceaccount.com"